Models/ErrorViewModel.cs
namespace MvcCoreUtilidades.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CachingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

namespace MvcCoreUtilidades.Controllers
{
    public class CachingController : Controller
    {
        private IMemoryCache memoryCache;

        public CachingController(IMemoryCache memoryCache)
        {
            this.memoryCache = memoryCache;
        }

        public IActionResult MemoriaDistribuida()
        {
            string fecha = DateTime.Now.ToLongDateString() + " -- " + DateTime.Now.ToLongTimeString();
            ViewData["FECHA"] = fecha;
            return View();
        }

        public IActionResult MemoriaPersonalizada(int? tiempo)
        {
            if (tiempo == null)
            {
                tiempo = 15;
            }
            string fecha = DateTime.Now.ToLongDateString() + " -- " + DateTime.Now.ToLongTimeString();

            // Vemos si existe algo en cache
            if (this.memoryCache.Get("FECHA") == null)
            {
                // No existe
                MemoryCacheEntryOptions options = new MemoryCacheEntryOptions().SetAbsoluteExpiration(TimeSpan.FromSeconds(tiempo.Value));
                this.memoryCache.Set("FECHA", fecha, options);
                ViewData["MWNSAJE"] = "Almacenado en cache";
                ViewData["FECHA"] = this.memoryCache.Get("FECHA");
            }
            else
            {
                // Existe fecha en cache
                fecha = this.memoryCache.Get<string>("FECHA");
                ViewData["MWNSAJE"] = "Recuperando de cache";
                ViewData["FECHA"] = this.memoryCache.Get("FECHA");
            }
            return View();
        }
    }
}

Controllers/CifradoController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreUtilidades.Helpers;

namespace MvcCoreUtilidades.Controllers
{
    public class CifradoController : Controller
    {
        public IActionResult CifradoBasico()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CifradoBasico(string contenido, string resultado, string accion)
        {
            string response = HelperCryptography.EncriptarTextoBasico(contenido);
            if(accion.ToLower() == "cifrar")
            {
                ViewData["TEXTOCIFRADO"] = response;
            }else if(accion.ToLower() == "comparar")
            {
                //Comparamos la respuesta cifrada con el valor de la caja resultado
                if(response != resultado)
                {
                    ViewData["MENSAJE"] = "Los valores no coinciden";
                }
                else
                {
                    ViewData["MENSAJE"] = "Contenidos iguales!!!1";
                }
            }
            return View();
        }

        public IActionResult CifradoEficiente()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CifradoEficiente(string contenido, string resultado, string accion)
        {
            if(accion.ToLower() == "cifrar")
            {
                string response = HelperCryptography.EncriptarContenido(contenido, false);
                ViewData["TEXTOCIFRADO"] = response;

            }
            else if (accion.ToLower() == "comparar")
            {
                string response = HelperCryptography.EncriptarContenido(contenido, true);
                if (response != resultado)
                {
                    ViewData["MENSAJE"] = "<h1 style='color:red'>Caballero los datos no son iguales >:( </h1>";
                }
                else
                {
                    ViewData["MENSAJE"] = "<h1 style='color:royalblue'>Todo Correcto Caballero</h1>";
                }
            }
            return View();
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreUtilidades.Models;
using System.Diagnostics;

namespace MvcCoreUtilidades.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MailExampleController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreUtilidades.Helpers;
using System.Net;
using System.Net.Mail;

namespace MvcCoreUtilidades.Controllers
{
    public class MailExampleController : Controller
    {
        private HelperUploadFiles helperUpload;
        private HelperMails helperMails;

        public MailExampleController(HelperMails helperMails, HelperUploadFiles helperUploadFiles)
        {
            this.helperMails = helperMails;
            this.helperUpload = helperUpload;
        }

        public IActionResult SendMail()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> SendMail(string para, string asunto, string mensaje, IFormFile file)
        {
            if (file != null)
            {
                string path = await this.helperUpload.UploadFileAsync(file, Folders.Mails);
                await this.helperMails.SendMailAsync(para, asunto, mensaje, path);
            }
            else
            {
                await this.helperMails.SendMailAsync(para, asunto, mensaje);
            }

            ViewData["MENSAJE"] = "Email enviado correctamente";

            return View();
        }
    }
}

Controllers/UploadFilesController.cs
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using MvcCoreUtilidades.Helpers;

public class UploadFilesController : Controller
{
    private HelperPathProvider helperPathProvider;

    public UploadFilesController(HelperPathProvider helperPathProvider)
    {
        this.helperPathProvider = helperPathProvider;
    }

    // Vista para subir un archivo
    public IActionResult SubirFichero()
    {
        return View();
    }

    // Método para manejar la subida de archivos mediante POST
    [HttpPost]
    public async Task<IActionResult> SubirFichero(IFormFile fichero)
    {
        // Obtener la ruta completa del archivo utilizando HelperPathProvider
        string path = this.helperPathProvider.MapPath(fichero.FileName, Folders.Uploads);

        // Subir el archivo utilizando Stream
        using (Stream stream = new FileStream(path, FileMode.Create))
        {
            // Copiar el contenido del archivo al stream
            await fichero.CopyToAsync(stream);
        }

        // Mensajes de éxito en la vista
        ViewData["MENSAJE"] = "Fichero subido a " + path;

        // Obtener y mostrar la URL base del servidor
        string urlServer = $"{HttpContext.Request.Scheme}://{HttpContext.Request.Host}";
        ViewData["TEST"] = urlServer;

        // Obtener y mostrar la URL completa del archivo
        string urlPath = this.helperPathProvider.MapUrlPath(fichero.FileName, Folders.Uploads);
        ViewData["URL"] = urlPath;

        return View();
    }

}

Views/Caching/MemoriaDistribuida.cshtml
<h1>Memoria distribuida</h1>
<p>
    <a asp-controller="Caching" asp-action="MemoriaDistribuida">
        Actualizar página
    </a>
</p>

<h2 style="color: royalblue">
    @ViewData["FECHA"]
</h2>

Views/Caching/MemoriaPersonalizada.cshtml
<h1>Memoria Personalizada</h1>

<p>
    <a asp-controller="Caching" asp-action="MemoriaPersonalizada" asp-route-tiempo="5">
        Actualizar página 5seg
    </a>
</p>
<p>
    <a asp-controller="Caching" asp-action="MemoriaPersonalizada" asp-route-tiempo="25">
        Actualizar página 25seg
    </a>
</p

<h1 style="color: crimson">
    @ViewData["MENSAJE"]
</h1>
<h1 style="color: royalblue">
    @ViewData["FECHA"]
</h1>

Views/Cifrado/CifradoBasico.cshtml
<h1>Cifrado básico</h1>

<form method="post">
    <label>Contenido a cifrar: </label>
    <input type="text" name="contenido" class="form-control" />
    <label>Resultado: </label>
    <textarea name="resultado" rows="5" class="form-control">@ViewData["TEXTOCIFRADO"]</textarea>
    <button name="accion" value="cifrar" class="btn btn-outline-success">
        Cifrar
    </button>
    <button name="accion" value="comparar" class="btn btn-outline-warning">
        Comparar
    </button>
</form>

<h1 style="color: royalblue">
    @ViewData["MENSAJE"]
</h1>

Views/Cifrado/CifradoEficiente.cshtml
<h1>Cifrado básico</h1>

<form method="post">
    <label>Contenido a cifrar: </label>
    <input type="text" name="contenido" class="form-control" />
    <label>Resultado: </label>
    <textarea name="resultado" rows="5" class="form-control">@ViewData["TEXTOCIFRADO"]</textarea>
    <button name="accion" value="cifrar" class="btn btn-outline-success">
        Cifrar
    </button>
    <button name="accion" value="comparar" class="btn btn-outline-warning">
        Comparar
    </button>
</form>

@Html.Raw(ViewData["MENSAJE"])

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/MailExample/SendMail.cshtml
<h1 style="color:blue">
    Send Mail NET CORE
</h1>

<form method="post" enctype="multipart/form-data">
    <label>Para: </label>
    <input type="text" name="para" class="form-control" />
    <label>Asunto:</label>
    <input type="text" name="asunto" class="form-control" />
    <label>Mensaje: </label>
    <textarea name="mensaje" class="form-control"></textarea>
    <label>Adjuntar archivo: </label>
    <input type="file" name="file" class="form-control" /> <br />
    <button class="btn btn-outline-success" style="width:100%">
        Enviar Mensaje
    </button>
</form>

<h1 style="color: royalblue">
    @ViewData["MENSAJE"]
</h1>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreUtilidades</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCoreUtilidades.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreUtilidades</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UploadFiles" asp-action="SubirFichero">SubirFichero</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MailExample" asp-action="SendMail">SendMail</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cifrado" asp-action="CifradoBasico">Cifrado Basico</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cifrado" asp-action="CifradoEficiente">Cifrado Eficiente</a>
                        </li
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Caching" asp-action="MemoriaPersonalizada">Memoria Personalizada</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Caching" asp-action="MemoriaDistribuida">Memoria Distribuida</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MvcCoreUtilidades - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/UploadFiles/SubirFichero.cshtml
<h1>Upload Files Net Core</h1>

<form method="post" enctype="multipart/form-data">
    <label>Seleccione un fichero</label>
    <input type="file" name="fichero" class="form-control" />
    <button class="btn btn-info">
        Subir fichero
    </button>
</form>
<img src=@ViewData["URL"]>
<h2 style="color:darkslateblue">
    @ViewData["MENSAJE"]
</h2> <br />
<h3>
    @ViewData["URL"]
</h3>
<h3>
    @ViewData["TEST"]
</h3>